<?php

namespace QuizBundle\Repository;

/**
 * OpcoesQuestaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpcoesQuestaoRepository extends \Doctrine\ORM\EntityRepository
{
}
