<?php

namespace QuizBundle\Repository;

/**
 * PesquisadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PesquisadorRepository extends \Doctrine\ORM\EntityRepository
{
}
