<?php

namespace QuizBundle\Repository;

/**
 * PesquisaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PesquisaRepository extends \Doctrine\ORM\EntityRepository
{
}
