<?php

namespace QuizBundle\Repository;

/**
 * QuestaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestaoRepository extends \Doctrine\ORM\EntityRepository
{
}
