<?php

namespace Ingresso\FinanceiroBundle\Repository;

/**
 * CartaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartaoRepository extends \Doctrine\ORM\EntityRepository
{
}
