<?php

namespace Ingresso\FinanceiroBundle\Repository;
use Doctrine\Common\Util\Debug;

/**
 * PagamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagamentoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQuantidadePagamento($lote)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('P')
            ->from('Ingresso\FinanceiroBundle\Entity\Pagamento', 'P')
            ->join('P.valores', 'V')
            ->where('V.lote = :lote')
            ->setParameter('lote', $lote);

        return $qb->getQuery()->getResult();
    }

    public function getPagamentoPorUsuario($usuario)
    {
        $qb = $this->_em->createQueryBuilder();
        $now = new \DateTime();

        $qb->select('P')
            ->from('Ingresso\FinanceiroBundle\Entity\Pagamento', 'P')
            ->join('P.valores', 'V')
            ->join('V.lote', 'L')
            ->join('L.evento', 'E')
            ->where('P.usuario = :usuario')
            ->andWhere('P.dataUtilizacao is null')
            ->andWhere('P.dataPagamento is not null')
            ->andWhere('E.dataEvento >= :now')
            ->setParameter('usuario', $usuario)
            ->setParameter('now', $now);

        return $qb->getQuery()->getResult();
    }
}
