<?php

namespace Ingresso\FinanceiroBundle\Repository;

/**
 * ValorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValorRepository extends \Doctrine\ORM\EntityRepository
{
}
