<?php

namespace Ingresso\EventoBundle\Repository;
use Doctrine\Common\Util\Debug;

/**
 * LoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoteRepository extends \Doctrine\ORM\EntityRepository {
	public function getLotePorEvento($evento) {
		$qb   = $this->_em->createQueryBuilder();
		$date = new \DateTime();

		$qb->select('L')
		   ->from('Ingresso\EventoBundle\Entity\Lote', 'L')
		   //->andWhere('L.ativo = :ativo')
		   //->andWhere('L.dataInicio <= :now')
		   //->andWhere('L.dataFim >= :now')
		   ->andWhere('L.evento = :evento')
		   //->setParameter('ativo', 1)
		   //->setParameter('now', $date)
		   ->setParameter('evento', $evento);

		return $qb->getQuery()->getResult();
	}
}
