<?php

namespace Ingresso\EventoBundle\Repository;

/**
 * SolicitacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
